# --- General options --- #
# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://creatorcao.github.io/"
baseurl: "https://creatorcao.github.io/creatorcao.github.io"

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
# title: "Ping Cao"

# Short description of your site
# description: "Hi, welcome to my space."

# Basic Site Settings
locale: "en-US"
#title: "creatorcao"
title_separator: "-"
name: &name "Ping Cao"
description: "During my internship as a medical student, the Dept. of Ob & Gyn was my first practice site where I gained most of the clinical experience. I still can remember the shock on the first sight of childbirth. What could be more sacred than to save the sick from suffering and to welcome a new life? It was also with this passion and interest that enabled me to choose Ob & Gyn in my postgraduate study. I received the supervision from the “IVF father” - Prof. Guanglun Zhuang and Prof. Yanwen Xu, who created the first PGT baby in China. I got the academic training regarding human reproduction and infertility treatment both theoretically and practically in the IVF center. My research background was reproductive genetics, exploring the role of gene polymorphism in controlled ovarian stimulation and embryo development. I realize that artificial intelligence would be the future for individualized treatment and embryo selection is still under much limitation and challenges. So I started excitingly to dive into deep learning like image recognition and computer vision, my aim is to train myself as a machine learning expert to push forward the application of artificial intelligence in ART. My PhD project is “Development of machine learning methods to study embryo morphokinetics and embryo implantation capacity”. I am grateful, motivated and inspired to work in Masoud’s brilliant young group."
url: https://creatorcao.github.io/  
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Your Sidebar Name"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Earth"
  employer         : "Red Brick University"
  uri              : # URL
  email            : "none@example.org" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : # URL
  orcid            : "http://orcid.org/yourorcidurl"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : "bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : "UniofOxford"  # Replace this with your X / Twitter handle
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # URL


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Blog: "https://creatorcao.github.io/tags/#machine-learning"
  Publications: "https://orcid.org/0000-0002-3049-7084"
  Aboutme: "https://www.zamanilab.org/ping-cao"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "https://github.com/creatorcao/creatorcao.github.io/assets/54368185/c5001fea-1565-4b1b-9251-cf7ec60f82b0"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#ffffff"
navbar-text-col: "#404040"
navbar-children-col: "#ffffff"
page-col: "#ffffff"
link-col: "#404040"
hover-col: "#0066cc"
footer-col: "#ffffff"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: cao

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
# rss: false
email: "cao_ping@foxmail.com"
# facebook: 
github: https://github.com/creatorcao
twitter: https://twitter.com/pingcao_
#  stackoverflow: " "
instagram: https://www.instagram.com/ping__cao
youtube: https://www.youtube.com/@ping-cao

# Select which share links to show in posts
share-links-active:
  twitter: https://twitter.com/pingcao_
  facebook: false
  google: false
  linkedin: https://www.linkedin.com/in/ping-cao/

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "creatorcao.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""
# If you want to use just-comments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
theme: PaperMod
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_main'
  media: 'images'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

theme: ["PaperMod"]
