title: I am a content creator.
description: 
github_username: 
hearder-img: images/post-bg-coffee.jpeg
url: "https://creatorcao.github.io/" 

sidebar: true   
sidebar-about-description:
sidebar-avatar: images/fox.jpeg

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

RSS: true

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
